SELECT
ITM.CATEGORY1 AS KATEGORÝLER, ITM.CATEGORY2 AS KULLANIM_KATEGORÝLERÝ,
ITM.CATEGORY3 AS ÜRÜN_BAZI_KATEGORÝLER, ITM.CATEGORY4 AS ÜRÜN_BAZI_KATEGORÝLER2,

SUM(OD.LINETOTAL) AS TOPLAM_SÝPARÝÞTUTARI,
SUM(OD.AMOUNT) AS TOPLAM_SÝPARÝÞADEDÝ,
COUNT(OD.ID) AS TOPLAM_SÝPARÝÞSAYISI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMAIRIMFIYAT
FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID 
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
	INNER JOIN CITIES CT ON CT.ID = A.CITYID 
	INNER JOIN TOWNS T ON T.ID = A.TOWNID 
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID 
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
-- WHERE ITM.CATEGORY1 LIKE '%SIG%'
WHERE ITM.CATEGORY1 = 'KOZMETIK'
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4
ORDER BY KULLANIM_KATEGORÝLERÝ DESC 