SELECT
DATEPART(MONTH,O.DATE_) AY,
DATEPART(YEAR,O.DATE_) AS YIL,
DATENAME(MONTH, O.DATE_) AS AY_ADI,

--SUM(OD.LINETOTAL) AS TOPLAM_TUTAR,
--SUM(OD.LINETOTAL)/NULLIF(SUM(OD.AMOUNT), 0) AS ORTALAMA_BIRIM_FIYAT,
--SUM(OD.AMOUNT)/NULLIF(COUNT(OD.ID), 0) AS SIPARIS_BASINA_URUN

SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI


FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID 
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
	INNER JOIN CITIES CT ON CT.ID = A.CITYID 
	INNER JOIN TOWNS T ON T.ID = A.TOWNID 
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID 
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

	--WHERE DATEPART(YEAR,O.DATE_)= 2019
	-- IKISINDEN BIRINI SEC
	--WHERE ITM.CATEGORY1 = 'GIDA'	

	GROUP BY DATEPART(MONTH,O.DATE_),DATENAME(MONTH, O.DATE_),DATEPART(YEAR,O.DATE_)
	ORDER BY DATEPART(MONTH,O.DATE_),DATENAME(MONTH, O.DATE_),DATEPART(YEAR,O.DATE_)
	--ORDER BY DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)
