SELECT
    ITM.CATEGORY1 AS CATEGORIES,
    ITM.CATEGORY2 AS USAGE_CATEGORIES,
    ITM.CATEGORY3 AS PRODUCT_SUBCATEGORIES,
    ITM.CATEGORY4 AS PRODUCT_SUBCATEGORIES2,

    SUM(OD.LINETOTAL) AS TOTAL_ORDER_AMOUNT,
    SUM(OD.AMOUNT) AS TOTAL_ORDER_QUANTITY,
    COUNT(OD.ID) AS TOTAL_ORDER_COUNT,
    SUM(OD.LINETOTAL) / SUM(OD.AMOUNT) AS AVERAGE_UNIT_PRICE

FROM ORDERS O
    INNER JOIN USERS U ON U.ID = O.USERID
    INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
    INNER JOIN CITIES CT ON CT.ID = A.CITYID
    INNER JOIN TOWNS T ON T.ID = A.TOWNID
    INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
    INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
    INNER JOIN INVOICES I ON I.ORDERID = O.ID
    INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
    INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

-- WHERE ITM.CATEGORY1 LIKE '%SIG%'  -- Uncomment to filter categories containing 'SIG'
WHERE ITM.CATEGORY1 = 'COSMETICS'    -- Filtering only 'COSMETICS' category

GROUP BY ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4

ORDER BY USAGE_CATEGORIES DESC
