SELECT
    DATEPART(MONTH,O.DATE_) AS MONTH,
    DATEPART(YEAR,O.DATE_) AS YEAR,
    DATENAME(MONTH, O.DATE_) AS MONTH_NAME,

    --SUM(OD.LINETOTAL) AS TOTAL_AMOUNT,
    --SUM(OD.LINETOTAL)/NULLIF(SUM(OD.AMOUNT), 0) AS AVERAGE_UNIT_PRICE,
    --SUM(OD.AMOUNT)/NULLIF(COUNT(OD.ID), 0) AS PRODUCT_PER_ORDER,

    SUM(OD.AMOUNT) AS TOTAL_ORDER_QUANTITY,
    COUNT(OD.ID) AS TOTAL_ORDER_COUNT

FROM ORDERS O
    INNER JOIN USERS U ON U.ID = O.USERID 
    INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
    INNER JOIN CITIES CT ON CT.ID = A.CITYID 
    INNER JOIN TOWNS T ON T.ID = A.TOWNID 
    INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID 
    INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
    INNER JOIN INVOICES I ON I.ORDERID = O.ID
    INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
    INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

    --WHERE DATEPART(YEAR,O.DATE_)= 2019  -- Select one of these filters
    --WHERE ITM.CATEGORY1 = 'FOOD'

GROUP BY 
    DATEPART(MONTH,O.DATE_),
    DATENAME(MONTH, O.DATE_),
    DATEPART(YEAR,O.DATE_)

ORDER BY 
    DATEPART(MONTH,O.DATE_),
    DATENAME(MONTH, O.DATE_),
    DATEPART(YEAR,O.DATE_)

-- Alternative ordering option:
-- ORDER BY DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)
