SELECT 
CT.CITY AS SEHIRADI,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI

	FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID 
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
	INNER JOIN CITIES CT ON CT.ID = A.CITYID 
	INNER JOIN TOWNS T ON T.ID = A.TOWNID 
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID 
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

	
GROUP BY  CT.CITY -- CT.CITY'E GÖRE SIRALAYACAK. ORDER BY SUM(OD.LINETOTAL) DESC; -- TOPLAM SÝPARÝÞ TUTARINA GÖRE BÜYÜKTEN KÜÇÜÐE DOÐRU GRUPLANDIRMA YAPAR.

--BU VERÝLEN ID KODUNA GÖRE ARAMA YAPAR: WHERE O.ID =26121
-- BU ÝÇÝNDEKÝ GÝRÝLEN ÝSME VEYA HARFE GÖRE ÇALIÞIR: WHERE U.NAMESURNAME LIKE '%Ceyda Gezginci%'
-- BU ÝÇÝNDEKÝ GÝRÝLEN ÝSME GÖRE ÇALIÞIR: WHERE U.NAMESURNAME = 'Ceyda Gezginci'

