SELECT 
  U.USERNAME_ AS USERNAME, 
  U.NAMESURNAME AS FULL_NAME, 
  CT.CITY AS CITY, 
  A.ADDRESSTEXT AS FULL_ADDRESS,
  O.ID AS ORDER_ID, 
  O.DATE_ AS ORDER_DATE,
  O.TOTALPRICE AS TOTAL_AMOUNT, 
  P.DATE_ AS PAYMENT_DATE, 
  I.DATE_ AS INVOICE_DATE, 
  ITM.ITEMCODE AS PRODUCT_CODE, 
  ITM.ITEMNAME AS PRODUCT_NAME,
  OD.AMOUNT AS QUANTITY,
  OD.UNITPRICE AS UNIT_PRICE,
  OD.LINETOTAL AS LINE_TOTAL

FROM ORDERS O
INNER JOIN USERS U ON U.ID = O.USERID 
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
INNER JOIN CITIES CT ON CT.ID = A.CITYID 
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE O.ID = 1
